theme: jekyll-theme-cayman
show_downloads: true
title: Sketch Plugin Manager
google_analytics: UA-81615963-2
icon: img/site-icon.svg
meta_keywords: sketch,sketch-plugin,plugin,manager,toolbox,sketchpacks,sketch-plugin-manager
summary_img: img/catalog-view.png
meta_author: Mel Ludowise
